name: Terraform CI integration dev

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code checkout
      uses: actions/checkout@v4
      with:
          ref: dev

    - name: List directory
      run: |
          ls 
          pwd 

    - name: Terraform Init
      run: |
          cd ./terraform
          terraform init
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          TF_VAR_admin_username: 'ubuntu'
          
    - name: Terraform Destroy
      run: |
          cd ./terraform
          terraform destroy -auto-approve
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          TF_VAR_admin_username: 'ubuntu'  

          
    - name: Terraform Plan
      run: |
          cd ./terraform
          terraform plan
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          TF_VAR_admin_username: 'ubuntu'
          
    # - name: Terraform Apply
    #   run: |
    #       cd ./terraform
    #       terraform apply -auto-approve
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    #       TF_ACTION_WORKING_DIR: 'terraform'
    #       TF_VAR_admin_username: 'ubuntu'
