name: Terraform CI integration

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code checkout
      uses: actions/checkout@v3
      
    - name: Terraform Init
      run: |
          cd ./Terraform
          terraform init
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'

