name: Terraform CI integration

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Code checkout
      uses: actions/checkout@v3
      
    - name: Change directory
      run: |
          cd ./terraform
      
    - name: Terraform Init
      # run: |
      #     cd ./terraform
      #     terraform init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'

